const needsNightLeadConsent = (phone) => {
	const timestamp = getQueryStringValue('timestamp'), // Allow forcing timestamp through query string.
		localDate = timestamp ? new Date(parseInt(timestamp)) : new Date(),
		targetTimezones = ['AST', 'EST', 'MST', 'CST'],
		areaCode = getAreaCode(phone),
		timezone = getTimezoneFromAreaCode(areaCode),
    timezoneAbbr = timezone ? timezone.abbr : '',
		timezoneName = timezone ? getTimezoneName(timezone) : null,
		militaryTime = {
			current: timezoneName
				? parseInt(localDate.toLocaleString('en-US', {
					timeZone: timezoneName,
					hour12: false,
					hour: '2-digit',
					minute: '2-digit',
				}).replace(':', ''))
				: 0,
			min: 2100,
			max: 2254,
		};

	if (! targetTimezones.includes(timezoneAbbr)) {
		return false;
	}

	// noinspection RedundantIfStatementJS
	if (militaryTime.current < militaryTime.min || militaryTime.current > militaryTime.max) {
		return false;
	}

	return true;
};

export default needsNightLeadConsent;

const getTimezoneFromAreaCode = (areaCode) => {
	// eslint-disable-next-line no-prototype-builtins
	if (areaCodeToTimezoneMap.hasOwnProperty(areaCode) && areaCodeToTimezoneMap[areaCode]) {
		return areaCodeToTimezoneMap[areaCode];
	}

	return null;
};

const areaCodeToTimezoneMap = {
	'201': { 'abbr': 'EST', 'state': 'New Jersey' },
	'202': { 'abbr': 'EST', 'state': 'District of Columbia' },
	'203': { 'abbr': 'EST', 'state': 'Connecticut' },
	'205': { 'abbr': 'CST', 'state': 'Alabama' },
	'206': { 'abbr': 'PST', 'state': 'Washington' },
	'207': { 'abbr': 'EST', 'state': 'Maine' },
	'208': { 'abbr': 'MST', 'state': 'Idaho' },
	'209': { 'abbr': 'PST', 'state': 'California' },
	'210': { 'abbr': 'CST', 'state': 'Texas' },
	'212': { 'abbr': 'EST', 'state': 'New York' },
	'213': { 'abbr': 'PST', 'state': 'California' },
	'214': { 'abbr': 'CST', 'state': 'Texas' },
	'215': { 'abbr': 'EST', 'state': 'Pennsylvania' },
	'216': { 'abbr': 'EST', 'state': 'Ohio' },
	'217': { 'abbr': 'CST', 'state': 'Illinois' },
	'218': { 'abbr': 'CST', 'state': 'Minnesota' },
	'219': { 'abbr': 'CST', 'state': 'Indiana' },
	'220': { 'abbr': 'EST', 'state': 'Ohio' },
	'224': { 'abbr': 'CST', 'state': 'Illinois' },
	'225': { 'abbr': 'CST', 'state': 'Louisiana' },
	'228': { 'abbr': 'CST', 'state': 'Mississippi' },
	'229': { 'abbr': 'EST', 'state': 'Georgia' },
	'231': { 'abbr': 'EST', 'state': 'Michigan' },
	'234': { 'abbr': 'EST', 'state': 'Ohio' },
	'239': { 'abbr': 'EST', 'state': 'Florida' },
	'240': { 'abbr': 'EST', 'state': 'Maryland' },
	'248': { 'abbr': 'EST', 'state': 'Michigan' },
	'251': { 'abbr': 'CST', 'state': 'Alabama' },
	'252': { 'abbr': 'EST', 'state': 'North Carolina' },
	'253': { 'abbr': 'PST', 'state': 'Washington' },
	'254': { 'abbr': 'CST', 'state': 'Texas' },
	'256': { 'abbr': 'CST', 'state': 'Alabama' },
	'260': { 'abbr': 'EST', 'state': 'Indiana' },
	'262': { 'abbr': 'CST', 'state': 'Wisconsin' },
	'267': { 'abbr': 'EST', 'state': 'Pennsylvania' },
	'269': { 'abbr': 'EST', 'state': 'Michigan' },
	'270': { 'abbr': 'CST', 'state': 'Kentucky' },
	'272': { 'abbr': 'EST', 'state': 'Pennsylvania' },
	'276': { 'abbr': 'EST', 'state': 'Virginia' },
	'281': { 'abbr': 'CST', 'state': 'Texas' },
	'301': { 'abbr': 'EST', 'state': 'Maryland' },
	'302': { 'abbr': 'EST', 'state': 'Delaware' },
	'303': { 'abbr': 'MST', 'state': 'Colorado' },
	'304': { 'abbr': 'EST', 'state': 'West Virginia' },
	'305': { 'abbr': 'EST', 'state': 'Florida' },
	'307': { 'abbr': 'MST', 'state': 'Wyoming' },
	'308': { 'abbr': 'CST', 'state': 'Nebraska' },
	'309': { 'abbr': 'CST', 'state': 'Illinois' },
	'310': { 'abbr': 'PST', 'state': 'California' },
	'312': { 'abbr': 'CST', 'state': 'Illinois' },
	'313': { 'abbr': 'EST', 'state': 'Michigan' },
	'314': { 'abbr': 'CST', 'state': 'Missouri' },
	'315': { 'abbr': 'EST', 'state': 'New York' },
	'316': { 'abbr': 'CST', 'state': 'Kansas' },
	'317': { 'abbr': 'EST', 'state': 'Indiana' },
	'318': { 'abbr': 'CST', 'state': 'Louisiana' },
	'319': { 'abbr': 'CST', 'state': 'Iowa' },
	'320': { 'abbr': 'CST', 'state': 'Minnesota' },
	'321': { 'abbr': 'EST', 'state': 'Florida' },
	'323': { 'abbr': 'PST', 'state': 'California' },
	'325': { 'abbr': 'CST', 'state': 'Texas' },
	'330': { 'abbr': 'EST', 'state': 'Ohio' },
	'331': { 'abbr': 'CST', 'state': 'Illinois' },
	'332': { 'abbr': 'EST', 'state': 'New York' },
	'334': { 'abbr': 'CST', 'state': 'Alabama' },
	'336': { 'abbr': 'EST', 'state': 'North Carolina' },
	'337': { 'abbr': 'CST', 'state': 'Louisiana' },
	'339': { 'abbr': 'EST', 'state': 'Massachusetts' },
	'346': { 'abbr': 'CST', 'state': 'Texas' },
	'347': { 'abbr': 'EST', 'state': 'New York' },
	'351': { 'abbr': 'EST', 'state': 'Massachusetts' },
	'352': { 'abbr': 'EST', 'state': 'Florida' },
	'360': { 'abbr': 'PST', 'state': 'Washington' },
	'361': { 'abbr': 'CST', 'state': 'Texas' },
	'364': { 'abbr': 'CST', 'state': 'Kentucky' },
	'380': { 'abbr': 'EST', 'state': 'Ohio' },
	'385': { 'abbr': 'MST', 'state': 'Utah' },
	'386': { 'abbr': 'EST', 'state': 'Florida' },
	'401': { 'abbr': 'EST', 'state': 'Rhode Island' },
	'402': { 'abbr': 'CST', 'state': 'Nebraska' },
	'404': { 'abbr': 'EST', 'state': 'Georgia' },
	'405': { 'abbr': 'CST', 'state': 'Oklahoma' },
	'406': { 'abbr': 'MST', 'state': 'Montana' },
	'407': { 'abbr': 'EST', 'state': 'Florida' },
	'408': { 'abbr': 'PST', 'state': 'California' },
	'409': { 'abbr': 'CST', 'state': 'Texas' },
	'410': { 'abbr': 'EST', 'state': 'Maryland' },
	'412': { 'abbr': 'EST', 'state': 'Pennsylvania' },
	'413': { 'abbr': 'EST', 'state': 'Massachusetts' },
	'414': { 'abbr': 'CST', 'state': 'Wisconsin' },
	'415': { 'abbr': 'PST', 'state': 'California' },
	'417': { 'abbr': 'CST', 'state': 'Missouri' },
	'419': { 'abbr': 'EST', 'state': 'Ohio' },
	'423': { 'abbr': 'EST', 'state': 'Tennessee' },
	'424': { 'abbr': 'PST', 'state': 'California' },
	'425': { 'abbr': 'PST', 'state': 'Washington' },
	'430': { 'abbr': 'CST', 'state': 'Texas' },
	'432': { 'abbr': 'CST', 'state': 'Texas' },
	'434': { 'abbr': 'EST', 'state': 'Virginia' },
	'435': { 'abbr': 'MST', 'state': 'Utah' },
	'440': { 'abbr': 'EST', 'state': 'Ohio' },
	'442': { 'abbr': 'PST', 'state': 'California' },
	'443': { 'abbr': 'EST', 'state': 'Maryland' },
	'456': null,
	'458': { 'abbr': 'PST', 'state': 'Oregon' },
	'463': { 'abbr': 'EST', 'state': 'Indiana' },
	'469': { 'abbr': 'CST', 'state': 'Texas' },
	'470': { 'abbr': 'EST', 'state': 'Georgia' },
	'475': { 'abbr': 'EST', 'state': 'Connecticut' },
	'478': { 'abbr': 'EST', 'state': 'Georgia' },
	'479': { 'abbr': 'CST', 'state': 'Arkansas' },
	'480': { 'abbr': 'MST', 'state': 'Arizona' },
	'484': { 'abbr': 'EST', 'state': 'Pennsylvania' },
	'500': null,
	'501': { 'abbr': 'CST', 'state': 'Arkansas' },
	'502': { 'abbr': 'EST', 'state': 'Kentucky' },
	'503': { 'abbr': 'PST', 'state': 'Oregon' },
	'504': { 'abbr': 'CST', 'state': 'Louisiana' },
	'505': { 'abbr': 'MST', 'state': 'New Mexico' },
	'507': { 'abbr': 'CST', 'state': 'Minnesota' },
	'508': { 'abbr': 'EST', 'state': 'Massachusetts' },
	'509': { 'abbr': 'PST', 'state': 'Washington' },
	'510': { 'abbr': 'PST', 'state': 'California' },
	'512': { 'abbr': 'CST', 'state': 'Texas' },
	'513': { 'abbr': 'EST', 'state': 'Ohio' },
	'515': { 'abbr': 'CST', 'state': 'Iowa' },
	'516': { 'abbr': 'EST', 'state': 'New York' },
	'517': { 'abbr': 'EST', 'state': 'Michigan' },
	'518': { 'abbr': 'EST', 'state': 'New York' },
	'520': { 'abbr': 'MST', 'state': 'Arizona' },
	'522': null,
	'530': { 'abbr': 'PST', 'state': 'California' },
	'531': { 'abbr': 'CST', 'state': 'Nebraska' },
	'533': null,
	'534': { 'abbr': 'CST', 'state': 'Wisconsin' },
	'539': { 'abbr': 'CST', 'state': 'Oklahoma' },
	'540': { 'abbr': 'EST', 'state': 'Virginia' },
	'541': { 'abbr': 'PST', 'state': 'Oregon' },
	'544': null,
	'551': { 'abbr': 'EST', 'state': 'New Jersey' },
	'559': { 'abbr': 'PST', 'state': 'California' },
	'561': { 'abbr': 'EST', 'state': 'Florida' },
	'562': { 'abbr': 'PST', 'state': 'California' },
	'563': { 'abbr': 'CST', 'state': 'Iowa' },
	'566': null,
	'567': { 'abbr': 'EST', 'state': 'Ohio' },
	'570': { 'abbr': 'EST', 'state': 'Pennsylvania' },
	'571': { 'abbr': 'EST', 'state': 'Virginia' },
	'573': { 'abbr': 'CST', 'state': 'Missouri' },
	'574': { 'abbr': 'EST', 'state': 'Indiana' },
	'575': { 'abbr': 'MST', 'state': 'New Mexico' },
	'580': { 'abbr': 'CST', 'state': 'Oklahoma' },
	'585': { 'abbr': 'EST', 'state': 'New York' },
	'586': { 'abbr': 'EST', 'state': 'Michigan' },
	'588': null,
	'601': { 'abbr': 'CST', 'state': 'Mississippi' },
	'602': { 'abbr': 'MST', 'state': 'Arizona' },
	'603': { 'abbr': 'EST', 'state': 'New Hampshire' },
	'605': { 'abbr': 'CST', 'state': 'South Dakota' },
	'606': { 'abbr': 'EST', 'state': 'Kentucky' },
	'607': { 'abbr': 'EST', 'state': 'New York' },
	'608': { 'abbr': 'CST', 'state': 'Wisconsin' },
	'609': { 'abbr': 'EST', 'state': 'New Jersey' },
	'610': { 'abbr': 'EST', 'state': 'Pennsylvania' },
	'611': null,
	'612': { 'abbr': 'CST', 'state': 'Minnesota' },
	'614': { 'abbr': 'EST', 'state': 'Ohio' },
	'615': { 'abbr': 'CST', 'state': 'Tennessee' },
	'616': { 'abbr': 'EST', 'state': 'Michigan' },
	'617': { 'abbr': 'EST', 'state': 'Massachusetts' },
	'618': { 'abbr': 'CST', 'state': 'Illinois' },
	'619': { 'abbr': 'PST', 'state': 'California' },
	'620': { 'abbr': 'CST', 'state': 'Kansas' },
	'623': { 'abbr': 'MST', 'state': 'Arizona' },
	'626': { 'abbr': 'PST', 'state': 'California' },
	'628': { 'abbr': 'PST', 'state': 'California' },
	'629': { 'abbr': 'CST', 'state': 'Tennessee' },
	'630': { 'abbr': 'CST', 'state': 'Illinois' },
	'631': { 'abbr': 'EST', 'state': 'New York' },
	'636': { 'abbr': 'CST', 'state': 'Missouri' },
	'641': { 'abbr': 'CST', 'state': 'Iowa' },
	'646': { 'abbr': 'EST', 'state': 'New York' },
	'650': { 'abbr': 'PST', 'state': 'California' },
	'651': { 'abbr': 'CST', 'state': 'Minnesota' },
	'657': { 'abbr': 'PST', 'state': 'California' },
	'660': { 'abbr': 'CST', 'state': 'Missouri' },
	'661': { 'abbr': 'PST', 'state': 'California' },
	'662': { 'abbr': 'CST', 'state': 'Mississippi' },
	'667': { 'abbr': 'EST', 'state': 'Maryland' },
	'669': { 'abbr': 'PST', 'state': 'California' },
	'678': { 'abbr': 'EST', 'state': 'Georgia' },
	'680': { 'abbr': 'EST', 'state': 'New York' },
	'681': { 'abbr': 'EST', 'state': 'West Virginia' },
	'682': { 'abbr': 'CST', 'state': 'Texas' },
	'700': null,
	'701': { 'abbr': 'CST', 'state': 'North Dakota' },
	'702': { 'abbr': 'PST', 'state': 'Nevada' },
	'703': { 'abbr': 'EST', 'state': 'Virginia' },
	'704': { 'abbr': 'EST', 'state': 'North Carolina' },
	'706': { 'abbr': 'EST', 'state': 'Georgia' },
	'707': { 'abbr': 'PST', 'state': 'California' },
	'708': { 'abbr': 'CST', 'state': 'Illinois' },
	'710': null,
	'712': { 'abbr': 'CST', 'state': 'Iowa' },
	'713': { 'abbr': 'CST', 'state': 'Texas' },
	'714': { 'abbr': 'PST', 'state': 'California' },
	'715': { 'abbr': 'CST', 'state': 'Wisconsin' },
	'716': { 'abbr': 'EST', 'state': 'New York' },
	'717': { 'abbr': 'EST', 'state': 'Pennsylvania' },
	'718': { 'abbr': 'EST', 'state': 'New York' },
	'719': { 'abbr': 'MST', 'state': 'Colorado' },
	'720': { 'abbr': 'MST', 'state': 'Colorado' },
	'724': { 'abbr': 'EST', 'state': 'Pennsylvania' },
	'725': { 'abbr': 'PST', 'state': 'Nevada' },
	'727': { 'abbr': 'EST', 'state': 'Florida' },
	'731': { 'abbr': 'CST', 'state': 'Tennessee' },
	'732': { 'abbr': 'EST', 'state': 'New Jersey' },
	'734': { 'abbr': 'EST', 'state': 'Michigan' },
	'737': { 'abbr': 'CST', 'state': 'Texas' },
	'740': { 'abbr': 'EST', 'state': 'Ohio' },
	'743': { 'abbr': 'EST', 'state': 'North Carolina' },
	'747': { 'abbr': 'PST', 'state': 'California' },
	'754': { 'abbr': 'EST', 'state': 'Florida' },
	'757': { 'abbr': 'EST', 'state': 'Virginia' },
	'760': { 'abbr': 'PST', 'state': 'California' },
	'762': { 'abbr': 'EST', 'state': 'Georgia' },
	'763': { 'abbr': 'CST', 'state': 'Minnesota' },
	'765': { 'abbr': 'EST', 'state': 'Indiana' },
	'769': { 'abbr': 'CST', 'state': 'Mississippi' },
	'770': { 'abbr': 'EST', 'state': 'Georgia' },
	'772': { 'abbr': 'EST', 'state': 'Florida' },
	'773': { 'abbr': 'CST', 'state': 'Illinois' },
	'774': { 'abbr': 'EST', 'state': 'Massachusetts' },
	'775': { 'abbr': 'PST', 'state': 'Nevada' },
	'779': { 'abbr': 'CST', 'state': 'Illinois' },
	'781': { 'abbr': 'EST', 'state': 'Massachusetts' },
	'785': { 'abbr': 'CST', 'state': 'Kansas' },
	'786': { 'abbr': 'EST', 'state': 'Florida' },
	'800': null,
	'801': { 'abbr': 'MST', 'state': 'Utah' },
	'802': { 'abbr': 'EST', 'state': 'Vermont' },
	'803': { 'abbr': 'EST', 'state': 'South Carolina' },
	'804': { 'abbr': 'EST', 'state': 'Virginia' },
	'805': { 'abbr': 'PST', 'state': 'California' },
	'806': { 'abbr': 'CST', 'state': 'Texas' },
	'808': { 'abbr': 'HAST', 'state': 'Hawaii' },
	'809': { 'abbr': 'AST' },
	'810': { 'abbr': 'EST', 'state': 'Michigan' },
	'812': { 'abbr': 'EST', 'state': 'Indiana' },
	'813': { 'abbr': 'EST', 'state': 'Florida' },
	'814': { 'abbr': 'EST', 'state': 'Pennsylvania' },
	'815': { 'abbr': 'CST', 'state': 'Illinois' },
	'816': { 'abbr': 'CST', 'state': 'Missouri' },
	'817': { 'abbr': 'CST', 'state': 'Texas' },
	'818': { 'abbr': 'PST', 'state': 'California' },
	'828': { 'abbr': 'EST', 'state': 'North Carolina' },
	'830': { 'abbr': 'CST', 'state': 'Texas' },
	'831': { 'abbr': 'PST', 'state': 'California' },
	'832': { 'abbr': 'CST', 'state': 'Texas' },
	'833': null,
	'843': { 'abbr': 'EST', 'state': 'South Carolina' },
	'844': null,
	'845': { 'abbr': 'EST', 'state': 'New York' },
	'847': { 'abbr': 'CST', 'state': 'Illinois' },
	'848': { 'abbr': 'EST', 'state': 'New Jersey' },
	'850': { 'abbr': 'CST', 'state': 'Florida' },
	'854': { 'abbr': 'EST', 'state': 'South Carolina' },
	'855': null,
	'856': { 'abbr': 'EST', 'state': 'New Jersey' },
	'857': { 'abbr': 'EST', 'state': 'Massachusetts' },
	'858': { 'abbr': 'PST', 'state': 'California' },
	'859': { 'abbr': 'EST', 'state': 'Kentucky' },
	'860': { 'abbr': 'EST', 'state': 'Connecticut' },
	'862': { 'abbr': 'EST', 'state': 'New Jersey' },
	'863': { 'abbr': 'EST', 'state': 'Florida' },
	'864': { 'abbr': 'EST', 'state': 'South Carolina' },
	'865': { 'abbr': 'EST', 'state': 'Tennessee' },
	'866': null,
	'870': { 'abbr': 'CST', 'state': 'Arkansas' },
	'872': { 'abbr': 'CST', 'state': 'Illinois' },
	'877': null,
	'878': { 'abbr': 'EST', 'state': 'Pennsylvania' },
	'880': null,
	'881': null,
	'888': null,
	'900': null,
	'901': { 'abbr': 'CST', 'state': 'Tennessee' },
	'903': { 'abbr': 'CST', 'state': 'Texas' },
	'904': { 'abbr': 'EST', 'state': 'Florida' },
	'906': { 'abbr': 'EST', 'state': 'Michigan' },
	'907': { 'abbr': 'AKST', 'state': 'Alaska' },
	'908': { 'abbr': 'EST', 'state': 'New Jersey' },
	'909': { 'abbr': 'PST', 'state': 'California' },
	'910': { 'abbr': 'EST', 'state': 'North Carolina' },
	'912': { 'abbr': 'EST', 'state': 'Georgia' },
	'913': { 'abbr': 'CST', 'state': 'Kansas' },
	'914': { 'abbr': 'EST', 'state': 'New York' },
	'915': { 'abbr': 'MST', 'state': 'Texas' },
	'916': { 'abbr': 'PST', 'state': 'California' },
	'917': { 'abbr': 'EST', 'state': 'New York' },
	'918': { 'abbr': 'CST', 'state': 'Oklahoma' },
	'919': { 'abbr': 'EST', 'state': 'North Carolina' },
	'920': { 'abbr': 'CST', 'state': 'Wisconsin' },
	'925': { 'abbr': 'PST', 'state': 'California' },
	'928': { 'abbr': 'MST', 'state': 'Arizona' },
	'929': { 'abbr': 'EST', 'state': 'New York' },
	'930': { 'abbr': 'EST', 'state': 'Indiana' },
	'931': { 'abbr': 'CST', 'state': 'Tennessee' },
	'934': { 'abbr': 'EST', 'state': 'New York' },
	'936': { 'abbr': 'CST', 'state': 'Texas' },
	'937': { 'abbr': 'EST', 'state': 'Ohio' },
	'938': { 'abbr': 'CST', 'state': 'Alabama' },
	'940': { 'abbr': 'CST', 'state': 'Texas' },
	'941': { 'abbr': 'EST', 'state': 'Florida' },
	'947': { 'abbr': 'EST', 'state': 'Michigan' },
	'949': { 'abbr': 'PST', 'state': 'California' },
	'951': { 'abbr': 'PST', 'state': 'California' },
	'952': { 'abbr': 'CST', 'state': 'Minnesota' },
	'954': { 'abbr': 'EST', 'state': 'Florida' },
	'956': { 'abbr': 'CST', 'state': 'Texas' },
	'959': { 'abbr': 'EST', 'state': 'Connecticut' },
	'970': { 'abbr': 'MST', 'state': 'Colorado' },
	'971': { 'abbr': 'PST', 'state': 'Oregon' },
	'972': { 'abbr': 'CST', 'state': 'Texas' },
	'973': { 'abbr': 'EST', 'state': 'New Jersey' },
	'978': { 'abbr': 'EST', 'state': 'Massachusetts' },
	'979': { 'abbr': 'CST', 'state': 'Texas' },
	'980': { 'abbr': 'EST', 'state': 'North Carolina' },
	'984': { 'abbr': 'EST', 'state': 'North Carolina' },
	'985': { 'abbr': 'CST', 'state': 'Louisiana' },
	'989': { 'abbr': 'EST', 'state': 'Michigan' },
};

const getTimezoneName = (timezoneMapItem) => {
  // eslint-disable-next-line no-prototype-builtins
  if (! timezoneMapItem || ! timezoneMapItem.hasOwnProperty('abbr')) {
    return null;
  }

  const abbrToNameMap = {
    'AKST': 'America/Anchorage',
    'AST': 'America/Dominica',
    'CST': 'America/Chicago',
    'EST': 'America/New_York',
    'HAST': 'Pacific/Honolulu',
    'MST': (timezoneMapItem.state === 'Arizona') ? 'America/Phoenix' : 'America/Denver',
  };

  return abbrToNameMap[timezoneMapItem.abbr];
};

const getQueryStringValue = (arg) => {
	let result = null,
		tmp = [];

	location.search
		.substr(1)
		.split('&')
		.forEach(function (item) {
			tmp = item.split('=');
			if (tmp[0] === arg) {
				result = decodeURIComponent(tmp[1]);
			}
		});

	return result;
};

const isUSPhone = (phone) => {
	const regex = /^([+]?1[\s]?)?((?:[(](?:[2-9]1[02-9]|[2-9][02-8][0-9])[)][\s]?)|(?:(?:[2-9]1[02-9]|[2-9][02-8][0-9])[\s.-]?)){1}([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2}[\s.-]?){1}([0-9]{4}){1}$/;
	return regex.test(phone);
};

const getAreaCode = (phone) => {
	return isUSPhone(phone) ? phone.replace(/\D/g, '').substr(1, 3) : '';
};
